spring.application.name=tienda_virtual

#Base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/db_security
spring.datasource.username=root
spring.datasource.password=${MYSQL_PWD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA para el desarrollo
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

spring.security.user.password=1234
spring.security.user.name=arlex

spring.jwt.key.private=2ef13c53296cf1bb0f32b7ff68b24bf58d52d86ba6e821ccf0db64a2010ee1c7
spring.jwt.user.generator=Backend-Arlex
